yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.page_error'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок группы',
        help_text='Добавьте название группы'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Слаг',
        help_text='Добавьте слаг'
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Добавьте описание'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        help_text='Добавьте дату публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Впишите имя автора поста'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name="Группа",
        help_text="Выберите группу"
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Комментарий'
    )
    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE
    )

yatube/posts/forms.py
from django.forms import ModelForm

from posts.models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from posts.forms import CommentForm, PostForm
from posts.models import Follow, Group, Post, User


def index(request):
    posts = Post.objects.all()
    post_list = Post.objects.order_by('-pub_date')
    paginator = Paginator(post_list, settings.LIMIT_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'posts': posts
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.order_by('-pub_date')
    paginator = Paginator(posts, settings.LIMIT_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, settings.LIMIT_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_count = posts.count()
    following = request.user.is_authenticated and (
        Follow.objects.filter(user=request.user, author=author).exists()
    )
    context = {
        'post_count': post_count,
        'posts': posts,
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    post_number = post.author.posts.count()
    comments = post.comments.all()
    context = {
        'post': post,
        'post_number': post_number,
        'comments': comments,
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    groups = Group.objects.all()
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(reverse('posts:profile',
                                kwargs={'username': request.user.username}))
    context = {
        'form': form,
        'groups': groups
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    groups = Group.objects.all()
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:index')
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.id)

    context = {
        'form': form,
        'groups': groups,
        'is_edit': True
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    authors_posts = Post.objects.filter(
        author__following__user=request.user
    ).all()
    paginator = Paginator(authors_posts, settings.LIMIT_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if request.user != author and not is_follower.exists():
        Follow.objects.create(user=request.user, author=author)
    return redirect(reverse('posts:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if is_follower.exists():
        is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block content %}
{% load thumbnail %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
              {% if is_edit %}
              Редактировать запись
              {% else %}
              Добавить запись
              {% endif %}
              </div>
              <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  {% for field in form%}
                  {% endfor %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста
                      <span class="required text-danger" >*</span>
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                        {% if form.text.value %}
                        {{ form.text.value }}
                        {% endif %}
                    </textarea>
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группы
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">Список групп</option>
                      {% for group in groups %}
                        <option
                        {% if group.id == form.group.value %}
                           selected
                        {% endif %}
                        value="{{ group.id }}">Группа: {{ group.title }}
                        </option>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      Картинка
                    </label>
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                        Сохранить
                        {% else %}
                        Добавить
                        {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Лента подписки{% endblock %}
{% block header %}Лента подписки{% endblock %}
{% block content %}
{% load thumbnail %}
{% load cache %}
{% cache 20 index_page %}
{% include 'includes/switcher.html' %}
  <div class="container py-5">
    <h1>Последние обновления автора</h1>
    {% for post in page_obj %}
    <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
          {% thumbnail post.image "100x100" crop="center" as im %}
            <img class='images' src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {% endthumbnail %}
        <p>{{ post.text }}</p>
          {% if post %}
            <a href="{% url 'posts:post_detail' post.id %}">
             подробная информация
            </a>
          {% endif %}
    </article>
      {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
      </a>
      {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
  </div>
  {% include 'includes/paginator.html'%}
{% endcache %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    <article>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
          {% thumbnail post.image "100x100" crop="center" as im %}
              <img class='images' src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {% endthumbnail %}
        <p>{{ post.text }}</p>     
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </article>
  </div>  
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
{% load thumbnail %}
{% load cache %}
{% cache 20 index_page %}
{% include 'includes/switcher.html' %}
  <div class="container py-5" >
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
    <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
          {% thumbnail post.image "100x100" crop="center" as im %}
            <img class='images' src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {% endthumbnail %}
        <p>{{ post.text }}</p>
          {% if post %}
            <a href="{% url 'posts:post_detail' post.id %}">
             подробная информация
            </a>
          {% endif %}
    </article>
      {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
      </a>
      {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
  </div>
{% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %} Пост {{ post.text|truncatewords:30 }} {% endblock %}
{% block content %}
{% load user_filters %}
{% load thumbnail %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
                Группа: {{ post.group }}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: <span>{{ post_number }}</span>
            </li>
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
           {{ post.text }}
          </p>
          {% if user == post.author %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              редактировать запись
            </a>
          {% endif %}
          {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                  {% csrf_token %}
                <div class="form-group mb-2">
                 {{ form.text|addclass:"form-control" }}
                </div>
               <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
          {% endif %}

          {% for comment in comments %}
            <div class="media mb-4">
             <div class="media-body">
              <h5 class="mt-0">
               <a href="{% url 'posts:profile' comment.author.username %}">
                 {{ comment.author.username }}
               </a>
              </h5>
                <p>
                  {{ comment.text }}
                </p>
             </div>
            </div>
          {% endfor %}
        </article>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block content %}
{% load thumbnail %}
<title>Профайл пользователя {{ user.username }}</title>
      <div class="container py-5">
        <h1>Все посты пользователя {{ author.username }} </h1>
        <h3>Всего постов: {{ post_count }} </h3>
          {% if user != author %}
            <li class="list-group-item">
            {% if following %}
             <a
                class="btn btn-lg btn-light"
                href="{% url 'posts:profile_unfollow' author.username %}" role="button"
             >
               Отписаться
             </a>
          {% else %}
             <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
             >
               Подписаться
             </a>
          {% endif %}
          {% endif %}
        <article>
          <ul>
          {% for post in page_obj %}
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
            {% thumbnail post.image "100x100" crop="center" as im %}
               <img class='images' src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
            {% endthumbnail %}
          <p>
              {{ post.text }}
          </p>
          {% if post %}
            <a href="{% url 'posts:post_detail' post.id %}">
             подробная информация
            </a>
          {% endif %}
        </article>
      {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
      </a>
      {% endif %}
      {% endfor %}
      </div>
{% endblock %}